FROM debian:bullseye

RUN apt-get update && apt-get install -y python3-pip \
    sudo \ 
    tcpdump \
    nano \ 
    vim

RUN pip install scapy

COPY scripts/base_script.py ./  \
     asset/DOMAINS.txt ./        \
     asset/SERVERS.txt ./


RUN chmod a+x base_script.py

