FROM debian:bullseye

RUN apt-get update && apt-get install -y python3-pip \
    sudo \ 
    tcpdump \
    nano \ 
    vim

RUN pip install scapy

ADD "scripts/base_script.py" "base_script"

RUN chmod a+x base_script

